image: node:20
pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install --force
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Prepare Build Directory
          script:
            - |
              ssh $USER@$SERVER << 'EOF'
                echo "Removing old build folder..."
                sudo rm -rf /var/www/html/tiptopnestjs/dist
                echo "Creating new build folder..."
                sudo mkdir /var/www/html/tiptopnestjs/dist
                echo "Setting folder permissions..."
                sudo chmod 777 /var/www/html/tiptopnestjs/dist
              EOF
      - step:
          name: Deploy artifacts using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: "/var/www/html/tiptopnestjs/dist"
                LOCAL_PATH: "dist/*"
            - echo "Pm2 restart"
            - ssh $USER@$SERVER "pm2 restart tiptopnestjs"

    dev:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install --force
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Prepare Build Directory
          script:
            - |
              ssh $USERDEV@$SERVERDEV << 'EOF'
                echo "Removing old build folder..."
                sudo rm -rf /var/www/html/dev/tiptopnestjs/dist
                echo "Creating new build folder..."
                sudo mkdir /var/www/html/dev/tiptopnestjs/dist
                echo "Setting folder permissions..."
                sudo chmod 777 /var/www/html/dev/tiptopnestjs/dist
              EOF
      - step:
          name: Deploy artifacts and restart PM2 on PROD
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $USERDEV
                SERVER: $SERVERDEV
                REMOTE_PATH: "/var/www/html/dev/tiptopnestjs/dist"
                LOCAL_PATH: "dist/*"
            - echo "Pm2 restart"
            - ssh $USERDEV@$SERVERDEV "pm2 restart tiptopnestjs-dev"
            
            
    staging:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install --force
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Prepare Build Directory
          script:
            - |
              ssh $USERSTAGING@$SERVERSTAGING << 'EOF'
                echo "Removing old build folder..."
                sudo rm -rf /var/www/html/stag/tiptopnestjs/dist
                echo "Creating new build folder..."
                sudo mkdir /var/www/html/stag/tiptopnestjs/dist
                echo "Setting folder permissions..."
                sudo chmod 777 /var/www/html/stag/tiptopnestjs/dist
              EOF
      - step:
          name: Deploy artifacts and restart PM2 on PROD
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $USERSTAGING
                SERVER: $SERVERSTAGING
                REMOTE_PATH: "/var/www/html/stag/tiptopnestjs/dist"
                LOCAL_PATH: "dist/*"
            - echo "Pm2 restart"
            - ssh $USERSTAGING@$SERVERSTAGING "pm2 restart tiptopnestjs-stag"